name: Task
Description: What needs to be done?
title: "[Task]: "
labels: ["task"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        What needs to be done?
    validations:
      required: true
